version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: mahi
      POSTGRES_PASSWORD: mahi
      POSTGRES_DB: mahi
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
